##
# @description Services (customizations for Dev Container)
# @author      C. M. de Picciotto <d3p1@d3p1.dev> (https://d3p1.dev/)
# @note        This file is intended to be used as an extension of the
#              mains/primaries `docker-compose.yml` and
#              `docker-compose.dev.yml`, i.e.:
#              `docker compose \
#               -f docker-compose.yml \
#               -f docker-compose.dev.yml \
#               -f docker-compose.devcontainer.yml \
#               up -d`
# @note        Customize PHP FPM service, so it is used
#              personalized Dev Container image
##
services:
  fpm_dev:
    image:
      d3p1/magento-php:${BASE_PHP_VERSION}-fpm-dev