##
# @description OpenSearch service
# @author      C. M. de Picciotto <d3p1@d3p1.dev> (https://d3p1.dev/)
# @note        This file is intended to be used as an extension of the 
#              main/primary `docker-compose.yml` 
#              (i.e.: using the `-f` flag in `docker compose up` command)
# @note        It is removed the `ulimits` setting recommended by the
#              documentation because it causes problems with 
#              Docker rootless mode
# @link        https://opensearch.org/docs/latest/install-and-configure/install-opensearch/docker/#sample-docker-composeyml
# @link        https://github.com/wazuh/wazuh-docker/issues/903#issuecomment-1798120664
# @link        https://github.com/moby/moby/issues/40942
##
services:
  web:
    depends_on:
      - opensearch
  
  opensearch:
    image:
      d3p1/magento-opensearch:2.5
    expose:
      - 9200
    volumes:
      - searchdata:/usr/share/opensearch/data
    env_file:
      - services/search/opensearch/.env
    restart:
      always

volumes:
  searchdata:
