##
# @description Elasticsearch service
# @author      C. M. de Picciotto <d3p1@d3p1.dev> (https://d3p1.dev/)
# @note        This file is intended to be used as an extension of the 
#              main/primary `docker-compose.yml` 
#              (i.e.: using the `-f` flag in `docker compose up` command)
# @note        It is removed the `ulimits` setting recommended by the
#              documentation because it causes problems with 
#              Docker rootless mode
# @link        https://www.elastic.co/guide/en/elasticsearch/reference/8.13/docker.html#_configure_and_start_the_cluster
# @link        https://github.com/wazuh/wazuh-docker/issues/903#issuecomment-1798120664
# @link        https://github.com/moby/moby/issues/40942
##
services:
  web:
    depends_on:
      - elasticsearch
  
  elasticsearch:
    image:
      d3p1/magento-elasticsearch:7.11
    expose:
      - 9200
    volumes:
      - searchdata:/usr/share/elasticsearch/data
    env_file:
      - services/search/elasticsearch/.env
    restart:
      always

volumes:
  searchdata:
