##
# @description Services (customizations for development)
# @author      C. M. de Picciotto <d3p1@d3p1.dev> (https://d3p1.dev/)
# @note        This file is intended to be used as an extension of the 
#              main/primary `docker-compose.yml`, i.e.:               
#              `docker compose \ 
#               -f docker-compose.yml \ 
#               -f docker-compose.dev.yml \
#               up -d`
# @note        Add file provider configuration to Traefik to be able to
#              use locally generated SSL certificates
# @note        Add Xdebug feature to `cli` and `cron` services
# @note        Add an PHP-FPM service called `fpm_xdebug` that
#              includes Xdebug feature.
#              I think that it is important to have another
#              service to attend Xdebug request because
#              Xdebug extension can cause performance issues.
#              In that way, the `fpm` container can continue
#              working as expected
# @note        It is not required to add the host map between the
#              container and the host (`host.docker.internal:host-gateway`),
#              so that Xdebug can connect to the IDE that is listening to it
#              on the host, because PHP base image entry points already
#              include that map
#@note         Xdebug used in PHP services must be configured
#              with `xdebug.client_host = host.docker.internal` so it connects
#              to the IDE in the host
# @note        Remove OPcache feature from `fpm`, `fpm_xdebug`, `cli`
#              and `cron` services to be development friendly
# @note        Add MailHog service to be able to work with emails locally
# @note        Mount host folder with developed code into containers
# @note        The service naming convention uses the 
#              underlying technology name for easy identification within 
#              the infrastructure stack. There is an exception for 
#              the `fpm_dev` and `fpm_xdebug` services.
#              The `fpm_dev` name was used to describe in a cleaner way
#              the container purpose.
#              The `fpm_xdebug` name is required because the
#              `web` service (Nginx) is configured to redirect Xdebug request
#              to this hostname
# @link        https://github.com/magento/magento-cloud-docker/blob/9998e5615a37cc584ac26b236104ae040aa6e0c5/images/nginx/1.24/Dockerfile#L4
# @link        https://github.com/magento/magento-cloud-docker/blob/9998e5615a37cc584ac26b236104ae040aa6e0c5/images/nginx/1.24/etc/vhost.conf#L41
# @link        https://github.com/magento/magento-cloud-docker/blob/9998e5615a37cc584ac26b236104ae040aa6e0c5/images/nginx/1.24/etc/xdebug-upstream.conf#L2
# @link        https://github.com/magento/magento-cloud-docker/blob/develop/images/php/fpm/docker-entrypoint.sh#L16
##
services:
  traefik:
    ports:
      - 8025:8025
    depends_on:
      - mailhog
    volumes:
      - ./services/traefik/etc:/etc/traefik
    environment:
      - TRAEFIK_ENTRYPOINTS_MAIL_ADDRESS=:8025
      - TRAEFIK_PROVIDERS_FILE_DIRECTORY=/etc/traefik/file-provider

  web:
    volumes:
      - ${BASE_DEV_DOC_ROOT_DIR}:/app
    environment:
      - WITH_XDEBUG=1

  fpm:
    volumes:
      - ${BASE_DEV_DOC_ROOT_DIR}:/app
    environment:
      - PHP_EXTENSIONS=bcmath bz2 calendar exif gd gettext intl mysqli pdo_mysql redis soap sockets sodium sysvmsg sysvsem sysvshm xsl zip pcntl

  fpm_xdebug:
    image:
      d3p1/magento-php:${BASE_PHP_VERSION}-fpm
    expose:
      - 9000
    volumes:
      - ${BASE_DEV_DOC_ROOT_DIR}:/app
    env_file:
      - services/magento/.env
    environment:
      - PHP_EXTENSIONS=bcmath bz2 calendar exif gd gettext intl mysqli pdo_mysql redis soap sockets sodium sysvmsg sysvsem sysvshm xsl zip pcntl xdebug
    labels:
      - traefik.enable=false
    restart:
      always

  fpm_dev:
    image:
      d3p1/magento-php:${BASE_PHP_VERSION}-fpm-dev
    expose:
      - 9000
    volumes:
      - ${BASE_DEV_DOC_ROOT_DIR}:/app
    env_file:
      - services/magento/.env
    labels:
      - traefik.enable=false
    profiles:
      - devcontainer
    restart:
      always

  cli:
    volumes:
      - ${BASE_DEV_DOC_ROOT_DIR}:/app
    environment:
      - PHP_EXTENSIONS=bcmath bz2 calendar exif gd gettext intl mysqli pdo_mysql redis soap sockets sodium sysvmsg sysvsem sysvshm xsl zip pcntl xdebug

  cron:
    volumes:
      - ${BASE_DEV_DOC_ROOT_DIR}:/app
    environment:
      - PHP_EXTENSIONS=bcmath bz2 calendar exif gd gettext intl mysqli pdo_mysql redis soap sockets sodium sysvmsg sysvsem sysvshm xsl zip pcntl xdebug

  mailhog:
    image:
      d3p1/magento-mailhog:1.0
    expose:
      - 1025
      - 8025
    labels:
      - traefik.http.routers.mail.entrypoints=mail
      - traefik.http.routers.mail.tls=true
      - traefik.http.routers.mail.rule=Host(`${BASE_DOMAIN}`) || Host(`www.${BASE_DOMAIN}`)
      - traefik.http.routers.mail.service=mail
      - traefik.http.services.mail.loadbalancer.server.port=8025
    restart:
      always