##
# @description Services (customizations for development)
# @author      C. M. de Picciotto <d3p1@d3p1.dev> (https://d3p1.dev/)
# @note        This file is intended to be used as an extension of the 
#              main/primary `docker-compose.yml`, i.e.:               
#              `docker compose \ 
#               -f docker-compose.yml \ 
#               -f docker-compose.dev.yml \
#               up -d`
# @note        Add file provider configuration to Traefik to be able to
#              use locally generated SSL certificates
# @note        Add Xdebug feature to `fpm`, `cli` and `cron` services.
#              Because of that, it is also added the host map between the
#              container and the host (`host.docker.internal:host-gateway`),
#              so Xdebug can connect to the IDE that is listening to it
#              on the host (Xdebug used in these services must be configured
#              with `xdebug.client_host = host.docker.internal` so it connects
#              to the IDE in the host)
# @note        Remove OPcache feature from `fpm`, `cli` and `cron` services
#              to be development friendly
# @note        Add MailHog service to be able to work with emails locally
# @note        Mount host folder with developed code into containers
# @note        The service naming convention uses the 
#              underlying technology name for easy identification within 
#              the infrastructure stack. There is an exception for 
#              the `fpm_dev` service. This name was used to describe
#              in a cleaner way the container purpose
# @link        https://github.com/magento/magento-cloud-docker/blob/9998e5615a37cc584ac26b236104ae040aa6e0c5/images/nginx/1.24/Dockerfile#L4
# @link        https://github.com/magento/magento-cloud-docker/blob/9998e5615a37cc584ac26b236104ae040aa6e0c5/images/nginx/1.24/etc/vhost.conf#L41
# @link        https://github.com/magento/magento-cloud-docker/blob/9998e5615a37cc584ac26b236104ae040aa6e0c5/images/nginx/1.24/etc/xdebug-upstream.conf#L2
##
services:
  traefik:
    ports:
      - 8025:8025
    depends_on:
      - mailhog
    volumes:
      - ./services/traefik/etc:/etc/traefik
    environment:
      - TRAEFIK_ENTRYPOINTS_MAIL_ADDRESS=:8025
      - TRAEFIK_PROVIDERS_FILE_DIRECTORY=/etc/traefik/file-provider

  web:
    volumes:
      - ${BASE_DEV_DOC_ROOT_DIR}:/app
    environment:
      - WITH_XDEBUG=1

  fpm:
    volumes:
      - ${BASE_DEV_DOC_ROOT_DIR}:/app
    environment:
      - PHP_EXTENSIONS="bcmath bz2 calendar exif gd gettext intl mysqli pdo_mysql redis soap sockets sodium sysvmsg sysvsem sysvshm xsl zip pcntl xdebug"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  fpm_dev:
    image:
      d3p1/magento-php:${BASE_PHP_VERSION}-fpm
    expose:
      - 9000
    volumes:
      - ${BASE_DEV_DOC_ROOT_DIR}:/app
    env_file:
      - services/magento/.env
    labels:
      - traefik.enable=false
    profiles:
      - devcontainer
    restart:
      always

  cli:
    volumes:
      - ${BASE_DEV_DOC_ROOT_DIR}:/app
    environment:
      - PHP_EXTENSIONS="bcmath bz2 calendar exif gd gettext intl mysqli pdo_mysql redis soap sockets sodium sysvmsg sysvsem sysvshm xsl zip pcntl xdebug"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  cron:
    volumes:
      - ${BASE_DEV_DOC_ROOT_DIR}:/app
    environment:
      - PHP_EXTENSIONS="bcmath bz2 calendar exif gd gettext intl mysqli pdo_mysql redis soap sockets sodium sysvmsg sysvsem sysvshm xsl zip pcntl xdebug"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mailhog:
    image:
      d3p1/magento-mailhog:1.0
    expose:
      - 1025
      - 8025
    labels:
      - traefik.http.routers.mail.entrypoints=mail
      - traefik.http.routers.mail.tls=true
      - traefik.http.routers.mail.rule=Host(`${BASE_DOMAIN}`) || Host(`www.${BASE_DOMAIN}`)
      - traefik.http.routers.mail.service=mail
      - traefik.http.services.mail.loadbalancer.server.port=8025
    restart:
      always